service: career
provider:
  name: aws
  runtime: python3.6
  region: us-west-2
functions:
  next:
    handler: handler.next
    events:
      - http:
          path: career/next
          method: get
